name: Falco libs QA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install kernel headers
      run: |
        sudo apt update
        sudo apt install -y linux-headers-$(uname -r)

    - name: Build builder image
      run: make builder

    - name: Build drivers
      uses: addnab/docker-run-action@v3
      with:
        image: libs-it-builder:latest
        options: -v {{ github.workspace }}/libs:/libs -v /usr/include/bpf:/usr/include/bpf:ro -v /lib/modules/:/lib/modules/:ro -v /usr/src/:/usr/src/:ro
        run: |
          cmake -S /libs \
            -DUSE_BUNDLED_DEPS=OFF \
            -DBUILD_BPF=ON \
            -B /libs/build
          make -C /libs/build/driver

    - name: Build userspace
      run: make userspace
