name: Falco libs QA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build and test Falco/libs
      run: |
        if [[ "$GITHUB_REF_NAME" == "master" ]]; then
          export SINSP_NO_CACHE="true"
          echo "Running without cache."
        fi

        PARALLEL_BUILDS="$(nproc)" make userspace
        make -C tests kmod-tests

    - name: Archive test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: |
          tests/report/

    - name: Login to Quay.io
      if: ${{ github.ref == '10/merge' }}
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Push builder cache
      if: ${{ github.ref_name == '10/merge' }}
      run: |
        docker tag \
          "quay.io/mmoltras/falco-libs-builder:$(git rev-parse HEAD)" \
          quay.io/mmoltras/falco-libs-builder:latest
        docker push quay.io/mmoltras/falco-libs-builder:latest

    - name: Push sinsp-example cache
      if: ${{ github.ref_name == '10/merge' }}
      run: |
        docker tag \
          "quay.io/mmoltras/sinsp-example:$(git rev-parse HEAD)" \
          quay.io/mmoltras/sinsp-example:latest
        docker push quay.io/mmoltras/sinsp-example:latest

    - name: Push runner cache
      if: ${{ github.ref_name == '10/merge' }}
      run: |
        docker tag \
          "quay.io/mmoltras/falco-test-runner:$(git rev-parse HEAD)" \
          quay.io/mmoltras/falco-test-runner:latest
        docker push quay.io/mmoltras/falco-test-runner:latest
