name: Falco libs QA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install kernel headers
      run: |
        sudo apt update
        sudo apt install -y linux-headers-$(uname -r)

    - name: Build builder image
      run: make builder

    - name: Build drivers
      run: make drivers

    - name: Build userspace
      run: make userspace
