name: Update libs

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Submodule update
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'molter73/falco-libs-qa'
      CHECKOUT_BRANCH: 'master'
      PR_AGAINST_BRANCH: 'master'
      OWNER: 'molter73'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update submodules
        id: run_action
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}
